### ISSUE TITLE
Bowtie fungal mapping, core functionality

### ISSUE THREAD

**Issue by kylebittinger** [zhaoc1/sunbeam_neutrino#1]
* For fungal alignments, search index should be constructed from all fungal genomes together.
* Suggest using SAM file directly to generate downstream files/graphs. 
* Columns 3 and 4 in the SAM file give the reference sequence and the position of the mapping -- these can be used to count total reads and build coverage plots in R.

**Comment by zhaoc1** [comment]
1. for all the interested fungal genomes, append the genome accession to the beginning of the contig accession number; cat into one fasta file.
2. Due to unmapped reads, as well as secondary alignments, we decided to use samtools and bedtools to get the information needed for downstream plots, including the mapped read counts and coverage per base.
